In [1]:
import numpy as np

In [2]:
array1d = np.array([1,2,3,4])
print(array1d)

[1 2 3 4]


In [3]:
type(array1d)

numpy.ndarray

In [4]:
array1d.ndim

1

In [5]:
arr2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
arr2d.size

8

In [7]:
arr2d.shape

(2, 4)

In [8]:
array1d.dtype

dtype('int32')