In [1]:
import numpy as np

In [2]:
mx = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
mx1= np.ones((4,5))
print(mx1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
mx2 = np.ones((3,4) , dtype = int)
print(mx2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
mx3 = np.zeros(5)
print(mx3)

[0. 0. 0. 0. 0.]


In [9]:
print(np.zeros((3,4), dtype = int))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
mx4 =np.empty((4,4))
print(mx4)

[[4.67296746e-307 1.69121096e-306 1.20161118e-306 4.45060607e-308]
 [1.78021119e-306 1.11256817e-306 1.06811422e-306 1.42417221e-306]
 [1.11260619e-306 8.90094053e-307 1.86919378e-306 1.06809792e-306]
 [1.37962456e-306 1.69111861e-306 1.78020169e-306 7.56605918e-307]]
