In [1]:
import numpy as np

# arrange()

In [10]:
arr = np.arange(1,7)
print(arr)

[1 2 3 4 5 6]


In [3]:
arr1 = np.arange(1,6,2)
print(arr1)

[1 3 5]


In [4]:
arr2 = np.arange(2,10,2)
print(arr2)

[2 4 6 8]


In [5]:
np.linspace(2,3,4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [6]:
np.linspace(1,2,1)

array([1.])

In [7]:
np.linspace(1,2,2)

array([1., 2.])

In [8]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [9]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [11]:
arr2d = arr.reshape(2,3)
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [22]:
arr2d.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
arr1d=np.arange(1,25)
print(arr1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [15]:
arr3d = arr1d.reshape(2,4,3)
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [17]:
arr33d=arr2d.reshape(1,2,3)
print(arr2d)
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


In [19]:
print(arr33d)

[[[1 2 3]
  [4 5 6]]]


In [20]:
arr33d.ravel()

array([1, 2, 3, 4, 5, 6])

In [21]:
arr3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])