In [1]:
import numpy as np
import random

In [6]:
np.random.random(1)
#np.random.random((0,1))

array([0.80300953])

In [7]:
np.random.random((3,3))

array([[0.63078864, 0.02278436, 0.6623271 ],
       [0.72108198, 0.1014582 , 0.92135897],
       [0.2627335 , 0.06063581, 0.236516  ]])

In [8]:
np.random.randint(1,4)

2

In [9]:
np.random.randint(1,4,(3,3))

array([[3, 2, 3],
       [1, 2, 3],
       [3, 1, 1]])

In [10]:
np.random.randint(1,4,(3,4))

array([[2, 1, 1, 3],
       [1, 2, 2, 2],
       [1, 3, 3, 2]])

In [11]:
np.random.randint(1,4,(3,3,3))

array([[[2, 3, 2],
        [2, 1, 1],
        [3, 3, 1]],

       [[1, 3, 1],
        [1, 3, 1],
        [1, 1, 1]],

       [[2, 3, 3],
        [3, 3, 1],
        [3, 1, 2]]])

In [12]:
np.random.seed(0)
np.random.randint(1,4,(3,3,3))

array([[[1, 2, 1],
        [2, 2, 3],
        [1, 3, 1]],

       [[1, 1, 3],
        [2, 3, 3],
        [1, 2, 2]],

       [[2, 2, 1],
        [2, 1, 1],
        [2, 3, 1]]])

In [13]:
np.random.seed(0)
np.random.randint(1,4,(3,3,3))

array([[[1, 2, 1],
        [2, 2, 3],
        [1, 3, 1]],

       [[1, 1, 3],
        [2, 3, 3],
        [1, 2, 2]],

       [[2, 2, 1],
        [2, 1, 1],
        [2, 3, 1]]])

In [14]:
np.random.rand(5)

array([0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [15]:
np.random.rand(2,3,3)

array([[[0.63992102, 0.14335329, 0.94466892],
        [0.52184832, 0.41466194, 0.26455561],
        [0.77423369, 0.45615033, 0.56843395]],

       [[0.0187898 , 0.6176355 , 0.61209572],
        [0.616934  , 0.94374808, 0.6818203 ],
        [0.3595079 , 0.43703195, 0.6976312 ]]])

In [19]:
np.random.randn(5,5)

array([[-0.02797118,  1.47598983,  0.6467801 , -0.36433431, -0.67877739],
       [-0.35362786, -0.74074747, -0.67502183, -0.13278426,  0.61980106],
       [ 1.79116846,  0.17100044, -1.72567135,  0.16065854, -0.85898532],
       [-0.20642094,  0.48842647, -0.83833097,  0.38116374, -0.99090328],
       [ 1.01788005,  0.3415874 , -1.25088622,  0.92525075, -0.90478616]])

x=[1,2,3,4]
np.random.choice(x)

In [20]:
x=[1,2,3,4]
np.random.choice(x)

2

In [21]:
x=[1,2,3,4]
np.random.choice(x)

1

In [24]:
x=[1,2,3,4]
np.random.permutation(x)

array([2, 3, 4, 1])

In [25]:
arr1=np.arange(1,17).reshape((4,4))
np.random.permutation(arr1)

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])